name: xtendly_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.3.2
  responsive_framework: ^0.2.0
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/items.json
