name: xtendly_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  badges: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  extended_wrap: ^0.1.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.3.2
  json_annotation: ^4.8.0
  material_design_icons_flutter: ^6.0.7096
  responsive_framework: ^0.2.0
  shimmer: ^2.0.0
  text_scroll: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  lint: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/items.json
    - assets/icons/
